In [1]:
import pandas as pd

In [2]:
used_cars = pd.read_csv("used_cars.csv")
used_cars

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [3]:
used_cars.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [4]:
used_cars.drop(['engine'], axis=1, inplace=True)

### Modifying data types so that data can be used for calculations later

In [5]:
used_cars['price'] = used_cars['price'].str.replace("$","").str.replace(",","")
used_cars['price'] = used_cars['price'].astype("int")

In [6]:
used_cars['milage'] = used_cars['milage'].str.replace("mi.","").str.replace(",","")
used_cars['milage'] = used_cars['milage'].astype("int")

In [7]:
used_cars['accident'] = used_cars['accident'].str.replace("None reported", "False").str.replace("At least 1 accident or damage reported", "True")
used_cars['accident'].astype("bool")
used_cars.fillna("No", inplace=True)

In [11]:
used_cars['data_year'] = 2023

In [12]:
used_cars

,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price,data_year
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,6-Speed A/T,Black,Black,True,Yes,10300,2023
1,Hyundai,Palisade SEL,2021,34742,Gasoline,8-Speed Automatic,Moonlight Cloud,Gray,True,Yes,38005,2023
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,Automatic,Blue,Black,False,No,54598,2023
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,7-Speed A/T,Black,Black,False,Yes,15500,2023
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,8-Speed Automatic,Glacier White Metallic,Black,False,No,34999,2023
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714,Gasoline,8-Speed Automatic with Auto-Shift,C / C,Hotspur,False,Yes,349950,2023
4005,Audi,S4 3.0T Premium Plus,2022,10900,Gasoline,Transmission w/Dual Shift Mode,Black,Black,False,Yes,53900,2023
4006,Porsche,Taycan,2022,2116,No,Automatic,Black,Black,False,No,90998,2023
4007,Ford,F-150 Raptor,2020,33000,Gasoline,A/T,Blue,Black,False,Yes,62999,2023
4008,BMW,X3 xDrive30i,2020,43000,Gasoline,A/T,Gray,Brown,True,Yes,40000,2023

In [13]:
used_cars.to_csv("kaggle_cars_cleaned.csv")